src/com/t_oster/visicut/gui/MainView.java

I have some improvements to the error handling of the "Capture image" button:
- clear background image after capture error
- close warning messages when the "Capture Image" button is pressed
- if the server answered with a HTTP 500 + message, show the message. With a small change to VisiCam, this could show the error messages like "marker not found" as a text message with some explanations, instead of an annoying "error image".
- improve the error messages (not just ImageIO exception, but the real reason like "no route to host")

Capture Image: improve error messages (part of #206)

---

src/com/t_oster/visicut/gui/MainView.java

as stated in https://github.com/t-oster/VisiCut/wiki/How-to-add-default-settings-for-your-lab 
this pull request will introduce the Fab Lab Berlin laser settings into visicut

added Fab Lab Berlin Visicut settings

---

src/com/t_oster/visicut/gui/MainView.java

We use VisiCut currently only with our lasercutter. This PR references our settings.
Next thing is to add a visicut drivers for a Goldcut ABH 721 cutter/plotter  -- that appears to be simple HPGL... 
I've also started tinkering with our iModela, and with a Silhouette Cameo. More to be added to the settings then.

Hello from Fab Lab Nuremberg

---

src/com/frochr123/periodictasks/RefreshCameraThread.java
src/com/t_oster/uicomponents/warnings/WarningPanel.java
src/com/t_oster/visicut/gui/MainView.java
src/com/t_oster/visicut/misc/DialogHelper.java

The camera code now shows at most one warning message, automatically replacing older messages. As soon as the image has been fetched successfully, old warnings are automatically closed.
This fixes #294 and the main problem described in #291.
Because I neither use nor really understand it, I have not tested the QR-reading code, which needed to be changed slightly. I roughly tested the image fetching code against a random webserver and a sometimes broken network connection.

Suppress duplicate camera warning messages

---

src/com/t_oster/visicut/gui/MainView.java

VisiCut should get the user's attention when it is called from the inkscape plugin. It now tries to get into foreground. Some window managers don't allow that, but then at least the VisiCut entry in the taskbar starts blinking.

Bring window to front when loading file from plugin

---

src/com/t_oster/visicut/gui/MainView.java

We've moved our settings repository into a Github Organisation, so this commit updates the URL that the settings are downloaded from.

Update Leeds Hackspace settings location

---

src/com/t_oster/visicut/managers/MappingManager.java

This a) is closer to what is needed most often,
and b) is much faster than having engrave3d first,
which needs long recalculation times when adjusting a mapping by color.
(Question remains, why engrave3d needs that recalculation time at all)

Sort default mappings, so that cut, mark and bend are first in the list.

---

src/com/t_oster/visicut/gui/MainView.java
src/com/t_oster/visicut/gui/resources/MainView.properties

The Zing lasercutter only shows the first 16 characters of a job name.
The 'ink_ext' prefix or filename are sometimes insufficient to clearly
distinguish jobs when navigating the job history on the lasercutter.
Especially, when the same object is sent multiple times with different
visicut-settings (engrave, cut, ...) it would be great, to give descriptive names, what the change was.
This commit provides a way for the user to add a short memonic text information
to the job name.
This helps for later retrieval from the job history and also
when multiple users send jobs with possibly similar jobs names.

Editable Job Name

---

src/com/t_oster/visicut/model/graphicelements/svgsupport/SVGImporter.java

Attention horror ahead. 
We had an drawn an object with inkscape that was shown 20% too big in visicut.
The file came originally from Adobe illustrator and uses px dimensions.
Inkscape is stupid enough to keep the Creator comment of Adobe for ever and then writes a standard 90 DPI svg with this comment still there.
My suggestion is to detect both Adobe comments and inkscape namespaces. Inkscape wins then.

fix DPI Adobe/Inkscape inconsistency

---

src/com/t_oster/visicut/gui/propertypanel/PropertiesPanel.java
src/com/t_oster/visicut/gui/propertypanel/PropertyPanel.java

It shows e.g. one stroke-color for cut, even if multiple stroke colors map to cut.
With this fix we list all selected filters for each property in the Laser Settings panel.
Less confusing to the user who selected multiple colors in 'mapping', but only sees the last one, when switching to 'Laser Settings'.
This fixes https://github.com/fablabnbg/VisiCut/issues/1

Properties Panel only shows one filter for each property.

---

src/com/t_oster/visicut/gui/MainView.java

Each time you run Export Laser Code, the JFileChooser starts at your home directory, rather than where you last saved a file.
This change makes the JFileChooser remember its last directory and file name, making it easy to export a job several times.

Remember the last used folder when exporting

---

src/com/t_oster/visicut/gui/mapping/PropertyMappingPanelTable.java

These appeared if you saved a plf with an enabled Everything Else mapping and reloaded it. Now the default entry is only added if it's not already found in the mapping list.

Suppress duplicate "Everything Else" mapping entries

---

src/com/t_oster/visicut/VisicutModel.java

Fixes issue #355. Java doesn't automatically destroy objects when they go out of scope, only when they are GC'ed. So we need to explicitly close the exported file.
Another solution would be to use try-with-resources, but that's java 7+.

Explicitly close gcode export file

---

src/com/t_oster/visicut/misc/Helper.java
tools/inkscape_extension/visicut_export.py

Fixes most of #361 - properly identifies the inkscape preferences directory using the same logic as inkscape itself, and handles the lack of the 64/32 redirection API on 32-bit XP.

Fix inkscape extension issues on XP

---

src/com/t_oster/visicut/gui/mapping/MappingPanel.java

Choosing a saved mapping with multiple entries and then pressing the "Edit" button right of the mapping selection dropdown list had no effect. Now it correctly shows the "custom mapping panel".

Fix edit button for saved mappings with multiple entries

---

src/com/t_oster/visicut/gui/MainView.java

I've added the repository for our Heidelberg Makerspace laser cutter settings.
We use a Epilog Legend 36 EXT.

Added repository for the "Heidelberg Makerspace" settings

---

src/com/t_oster/visicut/model/graphicelements/svgsupport/SVGImporter.java

Fixes https://github.com/fablabnbg/VisiCut/issues/7
I am unsure, if there are other cases, where UT_PERCENT is misinterpreted. Please double check!

Do not use width="100%" height="100%" for scaling when seen in document root

---

src/com/t_oster/visicut/model/graphicelements/svgsupport/SVGImporter.java

Inkscape 0.92 generates SVG in 96 DPI, all earlier version do 90 DPI.

Fix https://github.com/t-oster/VisiCut/issues/347

---

src/com/t_oster/visicut/gui/MainView.java

(currently only implemented for FAU FabLab)
If a PC has a matching hostname (FQDN), the "Download default settings" dialog defaults to the lab. This saves us some time because we have a separate account for each user, and we now lo longer have to tell every user to select the right lab.
Related to #375

Download settings: Pre-select lab based on FQDN

---

src/com/t_oster/uicomponents/warnings/WarningPanel.java

this error happened when quickly loading/adding multiple big files

Fix ConcurrentModificationException in WarningPanel.removeAllWarnings

---

src/com/t_oster/visicut/model/graphicelements/svgsupport/SVGImporter.java

Only warn about 72 DPI from Adobe Illustrator and 90 DPI from old inscape versions.
Files from inkscape 0.92 or later are silently(!) accepted as 96 DPI.
Files from unknown source are silently accepted as 90 DPI.
Other dubious 90 DPI sources should be added as theiy appear.

Do not warn about modern 96 DPI.

---

src/com/t_oster/visicut/gui/CamCalibrationDialog.java
src/com/t_oster/visicut/gui/MainView.java
src/com/t_oster/visicut/gui/resources/MainView.properties
src/com/t_oster/visicut/gui/resources/MainView_de_DE.properties
src/com/t_oster/visicut/gui/resources/MainView_fr_FR.properties
src/com/t_oster/visicut/gui/resources/MainView_it_IT.properties
src/com/t_oster/visicut/gui/resources/MainView_nl_NL.properties
src/com/t_oster/visicut/misc/DialogHelper.java

Make them more detailed for unusual ones (NullPointerException), and less detailed for others (No route to host).
Also translate the error message titles (TODO: translate to IT/NL/FR)
and always print a stack trace (in many cases, printStackTrace is now called twice, but IMHO that doesn't really matter)
Helps with debugging "Error: null" as in #295 
This is not entirely tested. It should not crash (that would be slightly embarassing), but it may show too long or too short messages in some cases.

Improve error messages for exceptions

---

src/com/t_oster/visicut/gui/MainView.java

Fixes the following when hitting "Calculate" or "Execute" when a profile DPI is readjusted.
java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
at com.t_oster.visicut.gui.MainView.getPropertyMapForCurrentJob(MainView.java:3635)
at com.t_oster.visicut.gui.MainView.access$6600(MainView.java:133)
at com.t_oster.visicut.gui.MainView$66.run(MainView.java:2758)

Fix crash when DPI changed in getPropertyMapForCurrentJob()

---

src/com/t_oster/visicut/model/graphicelements/GraphicSet.java
src/com/t_oster/visicut/model/graphicelements/svgsupport/SVGImage.java
src/com/t_oster/visicut/model/graphicelements/svgsupport/SVGObject.java

Now GraphicSet and its most important subclasses should be correctly threadsafe.

Fix more null pointer exceptions caused by thread-safety problems

---

src/com/t_oster/visicut/gui/ManageLasercuttersDialog.java

aborting the "Add Lasercutter" dialog caused java.lang.NullPointerException

Fix bug in Manage Lasercutter Dialog

---

src/com/t_oster/visicut/gui/MainView.java

and default to "maximized" if the previous setting is unknown or impossible (too large for the current screen).
Also correctly remember the size if the original window was placed outside the current screen coordinates (e.g. Linux two-screen setup, window on the second screen)

Remember if the window was maximized

---

distribute/distribute.sh
distribute/files/VisiCut.Linux
distribute/files/VisiCut.MacOS
distribute/windows/launcher.nsi
nbproject/project.properties
src/com/t_oster/visicut/VisicutModel.java
src/com/t_oster/visicut/gui/CamCalibrationDialog.java
src/com/t_oster/visicut/gui/VisicutApp.java
src/com/t_oster/visicut/gui/beans/PreviewPanel.java
src/com/t_oster/visicut/gui/beans/resources/PreviewPanel.properties
src/com/t_oster/visicut/misc/DialogHelper.java
src/com/t_oster/visicut/model/LaserProfile.java
src/com/t_oster/visicut/model/Raster3dProfile.java
src/com/t_oster/visicut/model/RasterProfile.java

This is an addition to my previous pullrequest (will rebase as soon as the other one is merged) with more discussion-worthy changes.
1. better antialiasing for the engrave preview by switching to a downscaled image if the user zooms out far enough
2. save some RAM by storing the (non-downscaled) raster preview as 1bit indexed (1 byte per pixel instead of 1 integer per pixel)
3. The heaviest change of this: switch from Thread.stop() to Thread.interrupt(), and dozens of interface changes to make the dithering interruptable and pass on InterruptedException. To be used together with the LibLaserCut pullrequest https://github.com/t-oster/LibLaserCut/pull/90 (compiles and works without, but the dithering will just go on without being interrupted). 
Please give feedback if this is the right …

Engrave preview and multiple other improvements

---

src/com/t_oster/visicut/managers/PreferencesManager.java

The fallback example settings (if no example directory was found, e.g. when starting from the source directory) did not create a material thickness, which triggered a warning.
Reproduce:
- Launch visicut via NetBeans IDE (or `ant run`)
- Options -> Download recommended settings  -> Example settings.
- Close and reopen
- Warning: Found material "Acrylic" without a thickness entry - this should not happen! Adding a thickness 0.0 for this material. Please report if you find a way to create materials without a thickness.

Bugfix: Missing thickness in fallback example settings

---

src/com/t_oster/visicut/model/graphicelements/svgsupport/SVGObject.java

Users of kyub.com report problems with VisiCut, because there was a bug with nested transformed groups. kyub exports SVG files with lots of such groups e.g. the numbers for assembly instructions.
<details><summary>Example SVG</summary>
<p>
```svg
<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" encoding="utf-8" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="841mm" height="594mm" viewBox="0 0 841 594">
<style type="text/css">.instructions {stroke:blue; stroke-width:0.01; fill:none}</style>
<g transform="translate(58.53,101.64) rotate(0)">
<path d="M-49.994,-10.639 L-48.011,-10.639 L-46.074,-10.714 L-44.173,-10.936 L-42.278,-11.311 L-40.437,-11.83 L-39.806,-12.062 …
```

Fix order of concatentation of nested transforms

---

tools/inkscape_extension/test.svg
tools/inkscape_extension/visicut_export.py

Inkscape 1.0, which is now near its alpha release, does no longer work with the commandline options we use for Inkscape <= 0.92. The extension now detects the Inkscape version and uses the appropriate commandline syntax.

Update Inkscape extension to work with version 1.0

---

src/com/t_oster/visicut/VisicutModel.java
src/com/t_oster/visicut/model/LaserProfile.java
src/com/t_oster/visicut/model/Raster3dProfile.java
src/com/t_oster/visicut/model/RasterProfile.java
src/com/t_oster/visicut/model/VectorProfile.java

- update LibLaserCut
- uses the new interface introduced in https://github.com/t-oster/LibLaserCut/pull/113

use new LibLaserCut interface: better spline interpolation for LTT laser

---

distribute/linux/description-pak

file was not modified since 2015 - see https://github.com/t-oster/VisiCut/commits/d0e9d529af2fc56e9f73c19f393ecc8feaf0c5ed/distribute/linux/description-pak so "soon" is rather misleading
Though maybe instead more supported devices should be listed instead.
BTW, is this software going to support ATMSolutions C02 PRO35 MINI connected via USB? Probably not, but if yes - then amending the description would be likely a good idea.

remove outdated info in linux description

---

src/main/java/de/thomas_oster/visicut/Preferences.java
src/main/java/de/thomas_oster/visicut/managers/PreferencesManager.java

This more or less fixes #546.
It's not the ideal solution which would be splitting the fields into two disjunct files, <del>because that is currently impossible due to a dependency deadlock (new NetBeans cannot edit old GUI, old NetBeans cannot edit Java11 code). I hope @t-oster will manage to sort that out some time, </del>but for now I propose the following workaround:
There are two files:
- settings.private.xml: all settings including local transient settings.
- settings.xml: all settings, but with local transient settings nulled out
VisiCut tries to load settings.private.xml if it exists and is newer, otherwise falls back to settings.xml. VisiCut always saves both files. The local settings.private.xml may be deleted at any time.
Ignoring that file is currently the user's …

Split settings into public and private part

---

distribute/files/VisiCut.Linux
distribute/files/VisiCut.MacOS

Show a warning if the Java version is below 10.
This needs to be tested on Mac before merging -- I don't have one.

Linux/Mac: Print and check Java version

---

.gitignore
src/com/t_oster/visicut/gui/ThreadUtils.java
src/main/java/com/frochr123/periodictasks/RefreshCameraThread.java
src/main/java/com/frochr123/qrcodescan/QRCodeScannerThread.java
src/main/java/de/thomas_oster/uicomponents/warnings/WarningPanel.java
src/main/java/de/thomas_oster/visicut/gui/MainView.java
src/main/java/de/thomas_oster/visicut/gui/ThreadUtils.java

This diagnoses and hopefully mostly fixes #538 . 
The crashes have a really low probability under Linux, but can be provoked by https://github.com/t-oster/VisiCut/commit/1c0b26bc78d65e9e511c41c1315daa76e9d9c3d0 .
In summary, we must never call GUI functions, e.g. `progressBar.setProgress()`, from any thread exept the Event Dispatcher Thread. This means that if we create a new thread, all GUI operations need to be encapsulated with `SwingUtilities.invokeAndWait` (or `invokeLater`). I wrote wrapper functions (ThreadUtils class) to make that easier: `assertInGUIThread` prints a warning if you are not in the right thread, and `runInGUIThread(()->{ progressBar.setProgress(42); });` calls `progressBar.setProgress(42);` in the GUI context (blocking until it finishes). The "weird syntax" …

Fix gui threadsafety

---

.gitignore
appimagecraft.yml
distribute/linux/Dockerfile.build-appimage
distribute/linux/build-appimage-in-docker.sh

Contributes to #565.
This PR adds support for [appimagecraft](https://github.com/TheAssassin/appimagecraft). To build AppImages, download appimagecraft (you can either install it via pip or just use the AppImages from its release page), and run it in the repository root directory.
As requested, I also added a Docker-based build script.

Add AppImage build scripts

---

src/main/java/de/thomas_oster/visicut/gui/MainView.java

Now Visicut will show exactly the same progress bar and message for "Export Laser Code" as it does for "Execute Job".
@t-oster This will cause a minor merge conflict with #564 - should I wait for that?

Fix #571: Show progress while saving file

---

src/main/java/de/thomas_oster/visicut/gui/beans/PreviewPanel.java
src/main/java/de/thomas_oster/visicut/misc/Homography.java

Rendering the background camera image takes very long, especially on 4K monitors. This is problematic because moving objects with the mouse has annoying lag. The background image is now cached if nothing changed, speeding up rendering times from ~100ms to ~10ms during a mouse drag operation.
I'm not sure if my solution is a good idea; it also needs some testing. I have left in some printf statements for debugging for now.
Any comments or ideas for a better solution?

Reduce lag when dragging objects in preview panel

---

src/main/java/de/thomas_oster/visicut/VisicutModel.java
src/main/java/de/thomas_oster/visicut/model/graphicelements/GraphicSet.java

Fixes #374 .
Holding on to the same transform reference as the GraphicSet being cloned is what caused the observed wonky behaviour.
I'm piggybacking a second commit to select the duplicated part because I feel it makes sense to match the behaviour of the 'add part' functionality.

Fixes #374: Duplicate element then non-drag reposition gets confused

---

distribute/windows/EnvVarUpdate.nsh

It's the first time I setup a development environment for VisiCut. I followed the developer guide and installed everything on Linux Mint 20.2
Error:
```
Determining Version (may be overridden with environment variable VERSION):
Version is: "1.9-121-g423e50d3+devel"
Building jar...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations …
```

fix "Error: unterminated string parsing" on distribute build for windows

---

.gitignore
appimagecraft.yml
distribute/linux/Dockerfile.build-appimage
distribute/linux/build-appimage-in-docker.sh

The appimagecraft config is outdated and doesn't work any more. This PR fixes the problems. It also takes the chance to update to a newer JRE.

Fix AppImage build

---

Makefile
distribute/distribute.sh

- Fix errors in distribute.sh
- Makefile / distribute.sh: Always update the splash screen, do not rely on cached image with possibly outdated version number
- distribute.sh: show where resulting EXE file was stored
VisicutBuilder must also be updated; a separate PR will follow.

Fix and improve build process

---

distribute/distribute-docker.sh
distribute/distribute.sh
distribute/linux/build-appimage-in-docker.sh
generateChangelog.sh
generatesplash.sh
test.sh
tools/cameraserver/capture.sh
tools/cameraserver/config.sh
tools/cameraserver/server.sh
tools/inkscape_extension/install.sh
tools/settings-maintenance/get-used-classes.sh

Two little changes to make shell scripts work more universally.
Not all Unixes have bash installed in /bin/bash; use the /usr/bin/env bash pattern to make finding it more platform independent.
The `which` command is deprecated in some Linux distributions (e.g. Debian); replacing it with more canonical command -v.

Don't assume hard-coded bash location. Replace `which` with `command`.

---

distribute/distribute.sh

This was inadvertently broken in 4bd60b0. The JRE is intended to be installed under Contents/Plugins/JRE, but the refactoring inadvertently made it be installed under Contents/Plugins only. In turn, this meant the launched script could no longer find the JRE and gave an error instead of starting the application.
Fixes #684.

Fix location of embedded JRE in macOS bundle

---

src/main/java/de/thomas_oster/visicut/gui/MainView.java

Currently visicut deletes the value, when a) the laser is changed, b) material is changed, or c) the mapping is changed.
This makes it tedious, if I want to e.g. laser the same file different mappings, which I frequently do. I'd prefer to just edit the prefix, instead of entering it again in full each time.
Preserving the text is also nicer in the case an inexperienced user wants to enter the job name before choosing a mapping.
Also, I suggest to insert a whitespace after the prefix to make it look nicer.

Suggest to preserve the user entered text  in the JobName TextField

---

src/main/java/de/thomas_oster/visicut/gui/mapping/MappingPanel.java

This PR improves usability of the MappingBox by saving a few mouse miles:
- whenever a file is loaded into visicut, the user has to choose a mapping. As this is a repetitive task, the clicks and mouse-movements should be as little as needed.
- with custom defined mappings, (which I frequently use) the user has to 1) click open the combo box, 2) move the mouse into the widget (or its scrollbar). 3) scroll down (using mouse wheel or drag). 4) click to choose the mapping.
This PR simply extends the scrollbox to 20 elements,
- we we have plenty of empty space below, it usually does not obscure anything
- in case of a very small screen, the scrollbox automatically opens upwards, going ca 350 pixels high. This should always fit on the screen.
- user interaction is reduced to two clicks: open, …

Enhancement: larger MappingBox

---

.github/workflows/external-buildserver.yml
.github/workflows/github-build.yml

(updated)
Add GitHub actions in parallel to the old buildserver.
Currently implemented:
- Trigger the old buildserver (unchanged) for every commit on master
- Run build pipeline on GH actions for every commit and PR
- Save output as build artifact (Note: artifacts are deleted after 90 days)
Not implemented:
- Permanent archive / release creation

build with GH actions and Docker

---

.github/workflows/github-build.yml
distribute/Dockerfile
distribute/distribute-docker.sh
distribute/distribute.sh
distribute/docker/maven-settings.xml
distribute/windows/installer.nsi

Fixes #670.
This PR introduces a GitHub actions workflow to create releases on GitHub with all the available binaries.
It is intended to replace the external VisiCut build server and make it easier for contributors to maintain their own builds without the need for external infrastructure and complicated setup procedures.
Please note that the second commit is a workaround for an NSIS bug. The generated license file contains non-ASCII characters (it is UTF-8 encoded). I cannot make NSIS accept the file as-is, it claims it violates codepage 0 (to my understanding, this is the currently active codepage; on Windows, it should be some UTF-8 compatible scheme; I have no idea what the default on Debian is, though).
A demo of the generated release can be found here: …

Release with GitHub actions

---

distribute/distribute.sh

Please see the diff for an in-depth explanation.
This should fix local builds, too. CC @jnweiger

Ignore continuous tag properly

---

distribute/mac/VisiCut.app/Contents/Info.plist

Fixes #738 informed by fix found over [here](https://github.com/streamlink/streamlink-twitch-gui/issues/1027#issuecomment-2449789501).

Fixed Mac OS environment permissions error when launching in Sequoia

---

src/main/java/de/thomas_oster/visicut/model/graphicelements/GraphicObject.java
src/main/java/de/thomas_oster/visicut/model/graphicelements/svgsupport/SVGShape.java
src/test/java/de/thomas_oster/visicut/model/graphicelements/SVGImportTest.java

For `<path transform="..." style="stroke-width:...">`, VisiCut ignored the `transform` when calculating the effective stroke width that is used to determine the bounding box.
As a result, some files showed way too large bounding boxes and could not be moved fully to the top left.

Fix #720: Bounding box calculation for paths with transform
