src/com/t_oster/visicut/gui/MainView.java
Added settings for FabLab RWTH Aachen
=> Added settings for FabLab RWTH Aachen: Update MainView.java

distribute/distribute.sh
with fakeroot, the .deb file can be built without sudo rights
=> build .deb package as non-root

src/com/t_oster/visicut/gui/MainView.java
just added the settings of FabLab Bremen to the presets, should be able to close #254
=> added FabLab Bremen settings to list

src/com/frochr123/periodictasks/RefreshCameraThread.java, src/com/t_oster/visicut/gui/MainView.java
- ignore 'marker not found' errors, just disable the image (only works with newest patches to VisiCam)
- ramp up the retry delay time after errors (first error: quick retry, later: wait 10 seconds more)
- handle closing the error message from the code, not via timeout. If fetching the image took very long and then failed, the error message kept disappearing and reappearing, causing annoying UI resizing.
The last point doesn't work perfecly yet, because when I tested it sometimes the error message was still open when the problem was gone. I don't know why because the code looks correct to me.
=> Improve camera error handling: Ignore 'marker not found', and more

src/com/t_oster/visicut/gui/PreviewPanelKeyboardMouseHandler.java, src/com/t_oster/visicut/gui/resources/PreviewPanelKeyboardMouseHandler.properties
* keep the object in the visible area, move the area if needed.
* add a right-click-menu item for rotate 90 deg.
=> scroll-move-rotate improvements

tools/inkscape_extension/visicut_export.py
Re-raised this since after amending the original commit, the pull request started pulling in other commits
For some versions of Windows 7, the query.exe is not installed if terminal services is not installed.
=> Fix for Windows 7 where terminal services is not installed

src/com/t_oster/visicut/VisicutModel.java, src/com/t_oster/visicut/gui/MainView.java
Ok, this is a beginning, to get the stone rolling. I've been implementing some things according to your advice https://github.com/t-oster/LibLaserCut/issues/32
The commits for LibLaserCut are in the separate repository, for suggestions on how to handle this, let me know.
=> Export gcode

src/com/tur0kk/thingiverse/ThingiverseClient.java, src/com/tur0kk/thingiverse/ThingiverseManager.java
Fixed thingiverse integration.
Changed app id, which I try to get approved by thingiverse.
=> fixed thingiverse login, switched to other app id

src/com/t_oster/visicut/gui/MainView.form, src/com/t_oster/visicut/gui/MainView.java
Fixes #337, allowing changes to be made in the gui editor without breaking the build.
Reverse engineered the problematic .java code changes back into the .form xml - well, pretty close anyway.
=> Bring MainView.form/MainView.java back into sync.

distribute/windows/installer.nsi, distribute/windows/launcher.nsi
=> Detect 64-bit JRE and JDK in windows installer and launcher

src/com/t_oster/visicut/managers/PreferencesManager.java
=> Fix example settings not working

src/com/t_oster/visicut/gui/MainView.java
This pull request fixes issue #368
=> Add default settings TkkrLab Enschede ( Fixes:  #368 )

LICENSE, lib/bridg-LICENSE.txt, lib/scribe-LICENSE.txt, lib/slf4j-LICENSE.txt, lib/webcam-capture-LICENSE.txt, lib/xpp3-LICENSE.txt, lib/xstream-LICENSE.txt
=> Comply with license attribution requirements for third party libraries

index.html
I collected all information from the old page which I found valuable and added it to the new github page. Fixes #233 (as soon as the old page and visicut.org point to the new github pages page).
=> Merge content of old website into index.html

src/com/t_oster/visicut/gui/CamCalibrationDialog.java, src/com/t_oster/visicut/gui/resources/CamCalibrationDialog.properties, src/com/t_oster/visicut/gui/resources/CamCalibrationDialog_de_DE.properties, src/com/t_oster/visicut/gui/resources/CamCalibrationDialog_fr_FR.properties, src/com/t_oster/visicut/gui/resources/CamCalibrationDialog_it_IT.properties, src/com/t_oster/visicut/gui/resources/CamCalibrationDialog_nl_NL.properties, src/com/t_oster/visicut/misc/DialogHelper.java
=> fix cam calibration "error null"

tools/inkscape_extension/visicut_export.py
Inkscape uses a random temporary filename for calling the extension. The extension now reads the original filename from the SVG and uses that to call Visicut.
I tested this under Linux and Windows.
Just as a note regarding the temporary files: Before, the extension created a temp file which was not cleaned up, now it creates a directory with one file which is also not cleaned up. Linux cleans /tmp on reboot, so it doesn't matter that we don't cleanup on our own, but Windows does not clean up %TMP% except if you manually launch the disk cleanup utility. But honestly I think this is not our problem... (If someone feels inclined, a solution might be scheduling the files for deletion upon the next reboot, which is possible by calling MoveFileEx with MOVEFILE_DELAY_UNTIL_REBOOT via the python …
=> inkscape extension: use real filename

src/com/t_oster/visicut/gui/MainView.java
A new lab with a Thunderlaser Nova 35
=> added settings link for FabLab Landkreis Fürth e.V.

src/com/t_oster/visicut/gui/MainView.java
=> Added Makerspace Dresden.

src/com/t_oster/visicut/gui/MainView.java
Sorry, there was an error in the Link. #451
=> Downloadlink corrected for Settings of Makerspace Dresden

src/com/t_oster/visicut/gui/MainView.java
=> Add setting for FabLab Chemillé en Anjou, sort settings list

src/com/t_oster/uicomponents/EditableTablePanel.form, src/com/t_oster/uicomponents/EditableTablePanel.java
Moved the save and revert button up to the other buttons.
=> Improvement for Gui buttons in editableTablePanel

src/com/t_oster/uicomponents/Ruler.java, src/com/t_oster/visicut/gui/MainView.java, src/com/t_oster/visicut/gui/PreviewPanelKeyboardMouseHandler.java, src/com/t_oster/visicut/gui/beans/PreviewPanel.java, src/com/t_oster/visicut/model/RasterProfile.java
I fixed some minor but annoying issues, and slightly refactored the RasterProfile rendering (to be used in a future pullrequest).
Feedback is appreciated.
(If possible please don't squash these commits into a large single one.)
=> Small fixes

src/com/t_oster/visicut/gui/MainView.java
The error message "camera image is null" is not so helpful, so I replaced it with something more useful.
=> Improve "Camera image is null" error message

distribute/files/examples/Laser-Script/LaserScriptSpeedtest.ls, src/com/t_oster/visicut/model/graphicelements/lssupport/LaserScriptImporter.java, src/com/t_oster/visicut/model/graphicelements/lssupport/ScriptInterfaceLogUi.java
Add the possibility of user input. An example file is included that tests a range of speeds and asks the user what's the desired range.
This pull requests depends on https://github.com/t-oster/LibLaserCut/pull/98 .
Documentation (to be added to the Wiki):
To ask for user input, use `prompt(question, defaultAnswer)`. For numbers, there is a corresponding `promptFloat(question, defaultAnswer)` function.
```
myString = prompt("What's your name", "<your name>");
myNumber = promptFloat("What's your favourite number", 123.45);
```
=> LaserScript: support `prompt(title, defaultValue)` to request user input

src/com/t_oster/visicut/misc/Helper.java, tools/inkscape_extension/visicut_export.py
make all the whitespace follow the usual python conventions (PEP8)
=> reformat Inkscape extension

src/com/t_oster/visicut/gui/MainView.java, src/com/t_oster/visicut/misc/Helper.java
wireless SSID seems like a good predictor for lab location.  I tested this on linux, but the mac one is just what the internet tells me should work.
=> Add an attempt to use SSID to guess recommended lab settings

src/main/java/de/thomas_oster/visicut/gui/MainView.java
@mgmax I am not so into the GUI Threading issue, but would it not be easy to just wrap all GUI modifying code in a
```
SwingUtilities.invokeLater(() -> {
//do GUI stuff here
});
```
Block like this?
At least in https://github.com/t-oster/LibLaserCut/pull/136#issuecomment-581126598 @tatarize gets warnings because the driver uses the progresslistener, which modifies the GUI
=> Fix GUI Thread Warnings

.travis.yml
This is just my experiments in order to get travis to build...
=> WIP: Travis CI -> Github Releases

README.md
fixing some markdown errors (mostly hyperlinks) with remark
=> Tidying up the readme

src/main/java/com/frochr123/fabqr/FabQRFunctions.java, src/main/java/de/thomas_oster/uicomponents/warnings/Message.java, src/main/java/de/thomas_oster/visicut/VisicutModel.java, src/main/java/de/thomas_oster/visicut/gui/MainView.java, src/main/java/de/thomas_oster/visicut/model/PlfFile.java
- Cleanup mostly in VisicutModel. Added type casts, and tidied up a few other things I forgot already and removed a fun redundant null check: p.getSourceFile() != null ? p.getSourceFile() : null
- Moved synchronized into method signature since all the blocks did was synchronize on `this`
- moved fields into top of class
- removed unused parameter
=> Code Cleanup

distribute/distribute.sh, distribute/files/plf-mime.xml, distribute/windows/installer.nsi, generateChangelog.sh, resources, tools/cameraserver/server.sh, tools/inkscape_extension/visicut_export.py
=> fixed typos && removed wrong file resources

src/main/java/de/thomas_oster/visicut/misc/LabSettings.java
=> Added ZAM to LabSettings List

src/main/java/de/thomas_oster/visicut/misc/LabSettings.java
Add a new link for SLU makerspace settings.
Took me a bit to find the new file location.. would be nice to update the example link in https://github.com/t-oster/VisiCut/wiki/How-to-add-default-settings-for-your-lab
=> Hghile visicut lab

pom.xml
Quick fixes https://github.com/t-oster/LibLaserCut/issues/196
=> Quick fix for t-oster/LibLaserCut#196 (support running on Java 17 on Linux)

.github/workflows/github-build.yml
Should fix build issues like in #721.
=> Fix release version detection

src/main/java/de/thomas_oster/visicut/VisicutModel.java, src/main/java/de/thomas_oster/visicut/gui/CamCalibrationDialog.java, src/main/java/de/thomas_oster/visicut/gui/MainView.java, src/main/java/de/thomas_oster/visicut/gui/VisicutApp.java, src/main/java/de/thomas_oster/visicut/gui/propertypanel/LaserPropertiesTableModel.java, src/main/java/de/thomas_oster/visicut/gui/propertypanel/PropertiesPanel.java, src/main/java/de/thomas_oster/visicut/gui/propertypanel/PropertyPanel.java, src/main/java/de/thomas_oster/visicut/managers/LaserPropertyManager.java, src/main/java/de/thomas_oster/visicut/model/LaserProfile.java, src/main/java/de/thomas_oster/visicut/model/Raster3dProfile.java, src/main/java/de/thomas_oster/visicut/model/RasterProfile.java, src/main/java/de/thomas_oster/visicut/model/VectorProfile.java
This cleanup makes working with them more convenient.
There will soon be a corresponding PR in LibLaserCut.
=> Move properties into separate package

src/main/java/de/thomas_oster/visicut/misc/LabSettings.java
Added LabSetting for xHain Hack+Makespace in Berlin, Germany
Fixed ident for Karlsruhe setting
=> Update LabSettings.java: add xHain Hack+Makespace Berlin

src/main/java/de/thomas_oster/visicut/misc/LabSettings.java
Hi,
we would like to add the settings for our Omtech Turbo-756 Laser to LabSettings.
=> Add FabLab Ansbach to LabSettings
